// Muster fuer Saetze, in die zur Laufzeit Werte eingesetzt werden (siehe i18n.js).
//
// Ein exakter Woerterbuch-Treffer scheitert hier, weil im DOM z.B. "Zuletzt geprueft: 18:42" steht.
// Reihenfolge zaehlt: das erste passende Muster gewinnt, deshalb stehen spezielle Faelle oben.

const USER_VERBS_EN = { deaktivieren: "disable", "löschen": "delete", herabstufen: "downgrade" };
const USER_VERBS_EN_PAST = { deaktivieren: "disabled", "löschen": "deleted", herabstufen: "downgraded" };

window.COCKPIT_PATTERNS_EN = [
  [/^Zuletzt geprüft: (.+)$/, "Last checked: $1"],
  [/^(\d+) von (\d+) Prüfungen bestanden$/, "$1 of $2 checks passed"],
  [/^Backend nicht erreichbar unter (.+)$/, "Backend unreachable at $1"],
  [/^Backend-Fehler \((\d+)\)$/, "Backend error ($1)"],
  [/^(.+): (.+) Vorhandene Daten können veraltet sein\.$/, "$1: $2 Existing data may be out of date."],
  [/^Weboberfläche erkannt: (.+) · Port (.+)$/, "Web interface detected: $1 · port $2"],
  [/^Raum „(.+)“ gespeichert\.$/, "Room “$1” saved."],
  [/^Backup „(.+)“ überschreibt die komplette Konfiguration dieses Routers und startet ihn sofort neu\.$/,
    "Backup “$1” will overwrite this router's entire configuration and restart it immediately."],
  [/^Der Dienst „(.+)“ kann den Router von außen erreichbar machen\.$/,
    "The “$1” service can make the router reachable from outside."],
  [/^Dieser Router wurde noch nie bestätigt\.\n\nSSH-Fingerprint \((.+)\):\n(.+)\n\n$/,
    "This router has never been confirmed.\n\nSSH fingerprint ($1):\n$2\n\n"],
  [/^Quellport (.+)$/, "Source port $1"],
  [/^Zielport (.+)$/, "Destination port $1"],
  [/^Uptime (.+)$/, "Uptime $1"],
  [/^(\d+) Einträge$/, "$1 entries"],
  [/^Kann den Zugang sperren oder das Netzwerk öffnen\.$/,
    "Can lock out access or open up the network."],

  // Sicherheits-Check: das Backend setzt Versionen, Tage und Dienstnamen ein.
  [/^(.+) ist noch an - diese alten Dienste übertragen Passwörter unverschlüsselt\. Schalte sie unter IP-Dienste aus, falls du sie nicht zwingend brauchst\.$/,
    "$1 is still switched on — those old services send passwords unencrypted. Turn them off under IP services unless you genuinely need them."],
  [/^(.+) installiert, (.+) verfügbar\.$/, "$1 installed, $2 available."],
  [/^Eine neuere RouterOS-Version \((.+)\) ist verfügbar, aktuell läuft (.+)\. Plane ein Update ein, aktuelle Versionen schließen bekannte Sicherheitslücken\.$/,
    "A newer RouterOS version ($1) is available; you are running $2. Plan an update — current versions close known security holes."],
  [/^RouterOS ist aktuell \((.+)\) - kein Update nötig\.$/,
    "RouterOS is up to date ($1) — no update needed."],
  [/^Noch aktiv: (.+)\.$/, "Still switched on: $1."],
  [/^VLAN (.+) ist bereits auf einem anderen Interface eingerichtet$/,
    "VLAN $1 is already configured on another interface"],
  [/^(.+) ist die aktuelle Version\.$/, "$1 is the current version."],
  [/^Letztes Backup ist (\d+) Tage alt\.$/, "Last backup is $1 days old."],
  [/^Letztes Backup ist (\d+) Tag\(e\) alt\.$/, "Last backup is $1 day(s) old."],
  [/^Das letzte Backup ist (\d+) Tage alt\. Erstelle ein neues, damit eine Wiederherstellung den aktuellen Stand trifft\.$/,
    "The last backup is $1 days old. Create a new one so a restore brings back the current state."],
  [/^Das letzte Backup ist (\d+) Tag\(e\) alt - aktuell genug\.$/,
    "The last backup is $1 day(s) old — recent enough."],
  [/^'room' darf höchstens (.+)$/, "'room' may be at most $1"],
  [/^Neue SSID für (.+)$/, "New SSID for $1"],
  [/^Neues Passwort für (.+)$/, "New password for $1"],
  [/^RouterOS ist aktualisiert, die RouterBOARD-Firmware \(Schritt 2 eines Updates\) noch nicht: (.+) läuft, (.+) liegt bereit\. Wende sie an und starte neu \(in Cockpit Pro unter Wartung > Firmware, sonst in WinBox unter System > RouterBOARD > Upgrade, danach Neustart\)\.$/,
    "RouterOS is updated, the RouterBOARD firmware (step 2 of an update) is not yet: $1 is running, $2 is ready. Apply it and restart (in Cockpit Pro under Maintenance > Firmware, otherwise in WinBox under System > RouterBOARD > Upgrade, then restart)."],
  // Das generische RouterOS-Muster muss hinter dem langen RouterBOARD-Satz stehen (erster Treffer gewinnt).
  [/^RouterOS (.+)$/, "RouterOS $1"],
  [/^(.+) aktiv, (.+) bereit\.$/, "$1 active, $2 ready."],
  [/^(.+) passt zu RouterOS\.$/, "$1 matches RouterOS."],
  [/^Die RouterBOARD-Firmware ist auf dem Stand von RouterOS \((.+)\), Schritt 2 des Updates ist erledigt\.$/,
    "The RouterBOARD firmware is at the RouterOS level ($1); step 2 of the update is done."],
  [/^(.+) bereit$/, "$1 ready"],
  // Benutzerverwaltung (Pro): Namen und Aktionen werden zur Laufzeit eingesetzt. Bei den drei
  // Sperrmeldungen ersetzt eine Funktion das deutsche Verb, weil ein "$1" es unuebersetzt liesse
  // (unbekanntes Verb bleibt stehen, damit die statische Pruefung mit Platzhaltern greift).
  [/^Eigene Gruppe: (.+)$/, "Custom group: $1"],
  [/^Zuletzt angemeldet (.+)$/, "Last login $1"],
  [/^Nur von (.+)$/, "Only from $1"],
  [/^Rechte von (.+)$/, "Rights of $1"],
  [/^Benutzer (.+) wurde angelegt\.$/, "User $1 was created."],
  [/^Benutzer (.+) gibt es schon$/, "User $1 already exists"],
  [/^Passwort für (.+) wurde gesetzt\.$/, "Password for $1 was set."],
  [/^Rechte von (.+) wurden geändert\.$/, "Rights of $1 were changed."],
  [/^(.+) verliert damit den Vollzugriff und kann keine Benutzer mehr verwalten\.$/, "$1 loses full access and can no longer manage users."],
  [/^(.+) kann sich danach nicht mehr am Router anmelden\. Der Zugang bleibt gespeichert und lässt sich wieder aktivieren\.$/,
    "$1 will no longer be able to log in to the router. The account stays saved and can be re-enabled."],
  [/^Der Benutzer (.+) wird endgültig vom Router entfernt\. Zum Sperren reicht auch Deaktivieren\.$/,
    "User $1 will be permanently removed from the router. Disabling is enough to block access."],
  [/^(.+) wurde aktiviert\.$/, "$1 was enabled."],
  [/^(.+) wurde deaktiviert\.$/, "$1 was disabled."],
  [/^(.+) wurde gelöscht\.$/, "$1 was deleted."],
  [/^Die Gruppe (.+) ist eine eigene Gruppe, Cockpit ändert sie nicht\.$/, "The group $1 is a custom group; Cockpit does not change it."],
  [/^Der angemeldete Benutzer kann sich nicht selbst (.+?)\.$/,
    (_match, verb) => `The logged-in user cannot ${USER_VERBS_EN[verb] || verb} itself.`],
  [/^(.+) ist der letzte aktive Benutzer mit vollen Rechten und lässt sich nicht (.+?)\. Lege zuerst einen weiteren an\. Benutzer in eigenen Gruppen zählt Cockpit dabei nicht mit\.$/,
    (_match, name, verb) => `${name} is the last active full-access user and cannot be ${USER_VERBS_EN_PAST[verb] || verb}. Create another one first. Users in custom groups do not count here.`],
  [/^Auf dem Router gibt es schon eine Gruppe (.+), die mehr darf als nur ansehen \((.+)\)\. Cockpit benutzt sie deshalb nicht\. Benenne sie in WinBox um oder entferne die Rechte\.$/,
    "The router already has a group $1 that may do more than view ($2). Cockpit therefore does not use it. Rename it in WinBox or remove those rights."],
  [/^Der andere Benutzer mit vollen Rechten war noch nie angemeldet\. Melde dich erst einmal mit ihm an, damit das Passwort nachweislich stimmt, dann lässt sich (.+) (.+?)\.$/,
    (_match, name, verb) => `The other full-access user has never logged in. Log in with it once first, so the password is proven to work, then ${name} can be ${USER_VERBS_EN_PAST[verb] || verb}.`],
];
